services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
  asynqmon:
    image: hibiken/asynqmon
    ports: 
      - "8081:8081"
    command:
      - --port=8081
      - --redis-url=redis://redis:6379/0
    depends_on:
      - redis


  api:
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      REDIS_URL: redis:6379
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - db
      - redis

volumes:
  data:
